name    'jalli-tree'
version '0.0.1'
source 'http://github.com/jalli/puppet-module-tree'
author 'jalli'
license 'GNU General Public License, Version 3.0'
summary 'Setup tree'
description 'Sets up tree which enables ASCII graphing directory structures'
project_page 'http://github.com/jalli/puppet-module-tree'
